### ISSUE TITLE
Using SDK with JDK 8 throws java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer

### ISSUE THREAD

**Issue by Inkon** [nemtech/symbol-sdk-java#213]
Creating transaction fail in some cases when running with JDK 8

```
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;

	at io.nem.core.utils.ByteUtils.bytesToInt(ByteUtils.java:91)
```

Possible solutions described here https://github.com/plasma-umass/doppio/issues/497

**Comment by fboucquez** [comment]
Hi @Inkon 0.16.3 version has been released with JDK 11 by mistake. We are working in a way to make JDK 11 compatible with JDK 8.

Could you try version 0.16.2 in your maven/gradle/sbt configuration? I'll close this issue once we have a newer than 0.16.3 version. 0.16.2 features are the same then 0.16.3.

**Comment by Inkon** [comment]
Thanks for quick reply. Yes, it works with older versions.
