### ISSUE TITLE
In the MerkelPathItem, the position variable should be an enum(Left, Right)

### ISSUE THREAD

**Issue by Wayonb** [nemtech/symbol-sdk-java#226]
In the MerkelPathItem the position is either left or right depending on position in the tree.  Making position an enum for better readability also matches the rest.

https://github.com/nemtech/nem2-sdk-java/blob/dd234b9558abe2db7d024757375a4cc3eb421c2e/sdk-core/src/main/java/io/nem/sdk/model/blockchain/MerkelPathItem.java#L5

**Comment by fboucquez** [comment]
Resolved in master, 0.17.0-SNAPSHOT
