### ISSUE TITLE
Rebranding

### ISSUE THREAD

**Issue by dgarcia360** [nemtech/symbol-sdk-java#228]
* [x] Rebranding branch created
  * [x] New design applied (font, logos, colors)
  * [x] Codename references renamed
  * [x] Ticker references renamed
  * [x] Links reviewed
  * [x] README reviewed
  * [x] Dependencies reviewed
  * [x] PR created
  * [x] Package renamed
  * [x] Package deployed

**Comment by fboucquez** [comment]
### Artifact names:

Proposed:

| Current Name | New Name |
| ------------- | ------------- |
| io.nem:api-jersey2-client  | io.nem:symbol-api-jersey2-client |                                 
| io.nem:api-okhttp-gson-client  | io.nem:symbol-okhttp-gson-client |                                 
| io.nem:api-vertx-client   | io.nem:symbol-api-vertx-client  |                                            
| io.nem:sdk-core   | io.nem:symbol-sdk-core   |                     
| io.nem:sdk-okhttp-client  | io.nem:symbol-sdk-okhttp-client  |                   
| io.nem:sdk-vertx-client  | io.nem:symbol-sdk-vertx-client |   
| io.nem:catbuffer  | io.nem:symbol-buffer? |

Artifact/Maven group id is `io.nem`. Should we create a separate group name like `io.nem.symbol` or keep the group  `io.nem` as the name could have the `symbol` prefix? 

AFIC, you cannot [delete](
https://stackoverflow.com/questions/9789611/removing-an-artifact-from-maven-central) or redeploy existing deployed artifacts in maven (nor NPM). We would just create a new version with a new name like `symbol-sdk-core` version `0.18.0` and move on.

### Packages:
Current SDK package names don't have nem2 or catapult. They are like this: `io.nem.sdk.model`, `io.nem.sdk.api`, `io.nem.core.math`. Should we add a `symbol` subpackage somewhere?

### Historical Data:

Should we patch historical data like Change Logs and PRs? I reckon they should stay the same and having the Symbol name in the new entries.

@dgarcia360 @evias @rg911

**Comment by rg911** [comment]
I'd go for `io.symbol.sdk` @dgarcia360 ?

**Comment by fboucquez** [comment]
I think both package and group id should start with `io.nem`,  nem as the organization name, not the platform. So package could be `io.nem.symbol`, `symbol` is part of `nem`

**Comment by fboucquez** [comment]
Snapshot has been deployed. Waiting for release publishing

**Comment by dgarcia360** [comment]
Missed this conversation. I'd go as well for `` io.nem.symbol``.

**Comment by fboucquez** [comment]
Thanks @dgarcia360 , we used `io.nem.symbol` in all 3 java artifacts (client, catbuffer and sdk)
