### ISSUE TITLE
numStatements is missing from the BlockInfo class

### ISSUE THREAD

**Issue by Wayonb** [nemtech/symbol-sdk-java#234]
The openapi define that the numStatements should also gets returned in the BlockInfo class.

https://github.com/nemtech/symbol-openapi/blob/964d5f857ce7369a41336dc1c33f6636275933c6/spec/core/block/schemas/BlockMetaDTO.yml#L23

**Comment by fboucquez** [comment]
TS bug https://github.com/nemtech/symbol-sdk-typescript-javascript/issues/464
