### ISSUE TITLE
aggregate transaction gets dropped when cosigners are added to the transaction.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/symbol-sdk-java#251]
The signed transaction that gets returned might fail since the maxFee might not be correct for the increase in transaction size.  
Should the signTransactionWithCosigners takes the network fee multipler to update the max fee?

There is also similar issue with JS version. 

    /**
     * Sign transaction with cosignatories creating a new SignedTransaction.
     *
     * @param initiatorAccount Initiator account
     * @param cosignatories The list of accounts that will cosign the transaction
     * @param generationHash the block 1 generation hash used to sign.
     * @return {@link SignedTransaction}
     */
    public SignedTransaction signTransactionWithCosigners(
        final Account initiatorAccount,
        final List<Account> cosignatories,
        final String generationHash) {
        SignedTransaction signedTransaction = this.signWith(initiatorAccount, generationHash);
        StringBuilder payload = new StringBuilder(signedTransaction.getPayload());

        for (Account cosignatory : cosignatories) {
            final DsaSigner signer = CryptoEngines.defaultEngine()
                .createDsaSigner(cosignatory.getKeyPair());
            byte[] bytes = ConvertUtils.fromHexToBytes(signedTransaction.getHash());
            byte[] signatureBytes = signer.sign(bytes).getBytes();
            payload.append(cosignatory.getPublicKey()).append(ConvertUtils.toHex(signatureBytes));
        }

        byte[] payloadBytes = ConvertUtils.fromHexToBytes(payload.toString());

        byte[] size = BigInteger.valueOf(payloadBytes.length).toByteArray();
        ArrayUtils.reverse(size);

        System.arraycopy(size, 0, payloadBytes, 0, size.length);

        return new SignedTransaction(initiatorAccount.getPublicAccount(),
            ConvertUtils.toHex(payloadBytes), signedTransaction.getHash(), getType());
    }

**Comment by fboucquez** [comment]
Unsure how to improve this one. Should the creator of the transaction be aware of the type of transaction and how it's going to be signed when creating it and setting up the max fee?

@Wayonb @dgarcia360 @dgarcia360

**Comment by Wayonb** [comment]
This could be fix by what we decide for Aggregate bonded transactions.  In that we figure out all the cosigner before hand.
Another option could be that as cosigners are added, the user also provides a fee multiplier which can be used to calculate the extra cost and update the max fee field. 
I am not sure which is best but personally I would prefer the transactions to also take a fee multiplier since it simplifies the max fee calculation.  Currently you have create the transaction twice.  Once to get the transaction size use to calculate the max fee field and then to create the transaction with the max fee.

**Comment by rg911** [comment]
> This could be fix by what we decide for Aggregate bonded transactions. In that we figure out all the cosigner before hand.
> Another option could be that as cosigners are added, the user also provides a fee multiplier which can be used to calculate the extra cost and update the max fee field.
> I am not sure which is best but personally I would prefer the transactions to also take a fee multiplier since it simplifies the max fee calculation. Currently you have create the transaction twice. Once to get the transaction size use to calculate the max fee field and then to create the transaction with the max fee.

Adding feeMultiplier into transaction would result in same behaviour, no? I cannot think a simple way to fix it, as when you serialise the transaction, if the new size changed due to cosigner get added, the signature and hash will be different?

**Comment by dgarcia360** [comment]
One costly option for the users would be adding `maxCosignaturesPerAggregate  * cosignatureSize` to the aggregate transaction size. Users are still able to pay fewer fees for the transaction by reducing the ``maxFee``.

MaxCosignaturesPerAggregate can be retrieved from https://github.com/nemtech/catapult-server/blob/master/resources/config-network.properties#L47

This change requires to have a configuration parameter on the SDK to define which is the default ``maxCosingaturesPerAggregate`` since it might vary per network. The value could also be retrieved from REST if not specified.

**Comment by evias** [comment]
What about using the multisig account graph to determine the _number of required_ signers ?

@Wayonb @fboucquez @rg911 http://api-01.us-west-1.symboldev.network:3000/account/TAWJ2M7BGKWGBPOUGD5NDKHYDDQ7OQD26HJMMQS2/multisig/graph

Knowing that aggregate bonded also have there own "announcement method". I can see this help because the account multisig *graph* can be iterated over to determine the needed *total* number of minApproval

**Comment by Wayonb** [comment]
Sorry for the late reply on this.

There are two issues.
1. Aggregate Complete
2. Aggregate Bonded.

This issue was open for 1.  I will open another issue for 2.

For this issue, all is required is that max fee includes the cosignatures that were added in the signTransactionWithCosigners.  We can talk about it in this week meeting.
