### ISSUE TITLE
The KECCAK_256 is removed from the lock hash algorithm type on the server side.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/symbol-sdk-java#265]
The SDK and server enum for lock hash does not match any more since KECCAK_256 was removed from the server side.

    /**
     * hashed using Keccak-256 (ETH Compat)
     */
    KECCAK_256(1),

https://github.com/nemtech/symbol-sdk-java/blob/6cbb34f8f6eb03698d5830748cfb95a0ce83cb56/sdk-core/src/main/java/io/nem/symbol/sdk/model/transaction/LockHashAlgorithmType.java#L34

**Comment by fboucquez** [comment]
Thanks @Wayonb, I think this is also an issue in open api

https://github.com/nemtech/symbol-openapi/blob/master/spec/plugins/lock_secret/schemas/LockHashAlgorithmEnum.yml#L10

@dgarcia360, should we remove the value from the spec? Do we need to reindex the number values?

**Comment by dgarcia360** [comment]
Thanks @Wayonb, the catbuffer schema was not updated either. 

I have submitted a PR: https://github.com/nemtech/catbuffer/pull/31/files
