### ISSUE TITLE
Notification from unconfirmedRemoved, partialRemoved and cosignature will be received by all registered address with the same web socket connection.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/symbol-sdk-java#273]
1. Expected behavior and actual behavior.
If multiple accounts register multiple accounts to listen to cosignature using one listener. They should only get notify for transactions that have their address.

2. Steps to reproduce the problem.
Register multiple accounts to listen to cosignature using one listener.

Does not filter using the user address.

    public Observable<CosignatureSignedTransaction> cosignatureAdded(Address address) {
        Validate.notNull(address, "Address is required");
        validateOpen();
        this.subscribeTo(ListenerChannel.COSIGNATURE + "/" + address.plain());
        return getMessageSubject()
            .filter(rawMessage -> rawMessage.getChannel().equals(ListenerChannel.COSIGNATURE))
            .map(rawMessage -> (CosignatureSignedTransaction) rawMessage.getMessage());
    }

**Comment by fboucquez** [comment]
This is blocked by rest, the SDKs don't have enough information in the WebSocket payload to route it to the right address when the same connection is used. We have the information for full transaction and status payloads but not for these ones.

**Comment by fboucquez** [comment]
Rest is working on the feature in https://github.com/nemtech/catapult-rest/issues/309

**Comment by fboucquez** [comment]
Rest branch ready to test https://github.com/nemtech/catapult-rest/tree/task/T309-enhance-ws-response-wih-topic
