### ISSUE TITLE
Use the account public key to retrieve account metadata for better performance

### ISSUE THREAD

**Issue by Wayonb** [nemtech/symbol-sdk-java#274]
When address is use as the account id(/metadata/account/<address>), rest has to resolve the address to a public key to find the metadata.  This look up is an extra DB query before actually getting the metadata for the account which can be prevented by just sending rest the account's public key. 

https://github.com/nemtech/symbol-sdk-java/blob/fedbc747c5991ab99de6ffe61e85f0b5d75e2f9a/sdk-core/src/main/java/io/nem/symbol/sdk/api/MetadataRepository.java#L40

**Comment by fboucquez** [comment]
We are using address elsewhere, why not using the address here too? Is this going to change when adding the pagination anyway?

**Comment by Wayonb** [comment]
@fboucquez Hold off on this change for now.  Currently public key is the primary key for lookup on  the server.  This might changed to address.  If it does then we can close this.

**Comment by fboucquez** [comment]
Hi @Wayonb , can we close this one? I think the server has moved towards the use of addresses

**Comment by Wayonb** [comment]
@fboucquez yes, closed
