### ISSUE TITLE
Delegated harvester transfer message does not match the server side.

### ISSUE THREAD

**Issue by Wayonb** [nemtech/symbol-sdk-java#332]
The message maker does not match the server side.  Also missed was the VRF changes requirements(same issue with JS).

https://docs.symbolplatform.com/catapult-whitepaper/main.pdf

**Comment by fboucquez** [comment]
@Wayonb could you describe better where doesn't match if you have your tests?

**Comment by fboucquez** [comment]
![image](https://user-images.githubusercontent.com/5390558/90050433-8e69b780-dcac-11ea-88d9-4cef44af3ccd.png)
