### ISSUE TITLE
All transaction related notification should take an unresolved address

### ISSUE THREAD

**Issue by Wayonb** [nemtech/symbol-sdk-java#342]
Currently all transaction related notification takes a resolved address(Address) as a filter.  This should actually be unresolved address.
From the whitepaper:

> The  topics  for  transaction  messages  consist  of  both  a  topic  marker  and  an  optional unresolved address filter. 

https://github.com/nemtech/symbol-sdk-java/blob/100d7aadd8e2b048a76f586605378fc9f089c038/sdk-core/src/main/java/io/nem/symbol/sdk/api/Listener.java#L69

**Comment by fboucquez** [comment]
@Wayonb atm the moment the topics use the plain address (SATNE7Q5BITMUTRRN6IB4I7FLSDRDWZA34I2PMQ), not the encoded one.  Example: "confirmed/SATNE7Q5BITMUTRRN6IB4I7FLSDRDWZA34I2PMQ". What's the format to be used when sending an alias/namespaceid? The encoded one?

**Comment by fboucquez** [comment]
This has been fixed at SDK level but I think it could be improved when rest accepts aliases.

https://github.com/nemtech/catapult-rest/issues/537

**Comment by fboucquez** [comment]
Fixed in dev
